version: "3.5"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jedai345
      MONGO_INITDB_DATABASE: demo
    volumes:
      - /MongoDB:/data/db
    networks:
      - desafio

networks:
  desafio:
